<?php
	
	declare(strict_types=1);
	
	namespace phpweb\Config;
	
	class ErrorRedirects
	{

		// ============================================================================
		// Major manual page modifications (need to handle shortcuts and pages in all languages)
		// Used permanent HTTP redirects, so search engines will be able to pick up the correct
		// new URLs for these pages.
		public const manual_page_moves = [
			// entry point changed
			'installation'                  => 'install',
			
			// was split among platforms (don't know where to redirect)
			'install.apache'                => 'install',
			'install.apache2'               => 'install',
			'install.netscape-enterprise'   => 'install',
			'install.otherhttpd'            => 'install',
			
			// moved to platform sections
			'install.caudium'               => 'install.unix.caudium',
			'install.commandline'           => 'install.unix.commandline',
			'install.fhttpd'                => 'install.unix.fhttpd',
			'install.hpux'                  => 'install.unix.hpux',
			'install.iis'                   => 'install.windows.iis',
			'install.linux'                 => 'install.unix',
			'install.omnihttpd'             => 'install.windows.omnihttpd',
			'install.openbsd'               => 'install.unix.openbsd',
			'install.sambar'                => 'install.windows.sambar',
			'install.solaris'               => 'install.unix.solaris',
			'install.xitami'                => 'install.windows.xitami',
			'install.windows.installer.msi' => 'install.windows',
			'install.windows.installer'     => 'install.windows',
			
			// Internals docs where moved
			'zend'                          => 'internals2.ze1.zendapi',
			'zend-api'                      => 'internals2.ze1.zendapi',
			'internals.pdo'                 => 'internals2.pdo',
			'phpdevel'                      => 'internals2.ze1.php3devel',
			'tsrm'                          => 'internals2.ze1.tsrm',
			
			// Replaced extensions
			'aspell'                        => 'pspell',
			
			// Refactored
			'regexp.reference'              => 'regexp.introduction',
		];

		// ============================================================================
		// Define shortcuts for PHP files, manual pages and external redirects
		public const uri_aliases = [
			
			# PHP page shortcuts
			'download'      => 'downloads',
			'getphp'        => 'downloads',
			'getdocs'       => 'download-docs',
			'documentation' => 'docs',
			'mailinglists'  => 'mailing-lists',
			'mailinglist'   => 'mailing-lists',
			'changelog'     => 'ChangeLog-7',
			'gethelp'       => 'support',
			'help'          => 'support',
			'unsubscribe'   => 'unsub',
			'subscribe'     => 'mailing-lists',
			'logos'         => 'download-logos',
			
			# manual shortcuts
			'intro'         => 'introduction',
			'whatis'        => 'introduction',
			'whatisphp'     => 'introduction',
			'what_is_php'   => 'introduction',
			
			'windows' => 'install.windows',
			'win32'   => 'install.windows',
			
			'globals'                                => 'language.variables.predefined',
			'register_globals'                       => 'security.globals',
			'registerglobals'                        => 'security.globals',
			'manual/en/security.registerglobals.php' => 'security.globals', // fix for 4.3.8 configure
			'magic_quotes'                           => 'security.magicquotes',
			'magicquotes'                            => 'security.magicquotes',
			'gd'                                     => 'image',
			'bcmath'                                 => 'bc',
			'streams'                                => 'book.stream',
			'mongodb'                                => 'set.mongodb',
			
			'callback' => 'language.pseudo-types',
			'number'   => 'language.pseudo-types',
			'mixed'    => 'language.pseudo-types',
			'bool'     => 'language.types.boolean',
			'boolean'  => 'language.types.boolean',
			'int'      => 'language.types.integer',
			'integer'  => 'language.types.integer',
			'float'    => 'language.types.float',
			'string'   => 'language.types.string',
			'heredoc'  => 'language.types.string',
			'<<<'      => 'language.types.string',
			'object'   => 'language.types.object',
			'null'     => 'language.types.null',
			'callable' => 'language.types.callable',
			
			'htaccess'  => 'configuration.changes',
			'php_value' => 'configuration.changes',
			
			'ternary'    => 'language.operators.comparison',
			'instanceof' => 'language.operators.type',
			'if'         => 'language.control-structures',
			'static'     => 'language.variables.scope',
			'global'     => 'language.variables.scope',
			'@'          => 'language.operators.errorcontrol',
			'&'          => 'language.references',
			'**'         => 'language.operators.arithmetic',
			'...'        => 'functions.arguments',
			'splat'      => 'functions.arguments',
			
			'dowhile' => 'control-structures.do.while',
			
			'tut'     => 'tutorial',
			'tut.php' => 'tutorial', // BC
			
			'faq.php'       => 'faq',      // BC
			'bugs.php'      => 'bugs',     // BC
			'bugstats.php'  => 'bugstats', // BC
			'docs-echm.php' => 'download-docs', // BC
			
			'odbc' => 'uodbc', // BC
			
			'links'     => 'support', // BC
			'links.php' => 'support', // BC
			'oracle'    => 'oci8',
			'_'         => 'function.gettext',
			'cli'       => 'features.commandline',
			
			'oop4' => 'language.oop',
			'oop'  => 'language.oop5',
			
			'const'                    => 'language.constants.syntax',
			'class'                    => 'language.oop5.basic',
			'new'                      => 'language.oop5.basic',
			'extends'                  => 'language.oop5.basic',
			'clone'                    => 'language.oop5.cloning',
			'construct'                => 'language.oop5.decon',
			'destruct'                 => 'language.oop5.decon',
			'public'                   => 'language.oop5.visibility',
			'private'                  => 'language.oop5.visibility',
			'protected'                => 'language.oop5.visibility',
			'var'                      => 'language.oop5.visibility',
			'abstract'                 => 'language.oop5.abstract',
			'interface'                => 'language.oop5.interfaces',
			'interfaces'               => 'language.oop5.interfaces',
			'autoload'                 => 'language.oop5.autoload',
			'__autoload'               => 'language.oop5.autoload',
			'language.oop5.reflection' => 'book.reflection', // BC
			'::'                       => 'language.oop5.paamayim-nekudotayim',
			
			'__construct'  => 'language.oop5.decon',
			'__destruct'   => 'language.oop5.decon',
			'__call'       => 'language.oop5.overloading',
			'__callstatic' => 'language.oop5.overloading',
			'__get'        => 'language.oop5.overloading',
			'__set'        => 'language.oop5.overloading',
			'__isset'      => 'language.oop5.overloading',
			'__unset'      => 'language.oop5.overloading',
			'__sleep'      => 'language.oop5.magic',
			'__wakeup'     => 'language.oop5.magic',
			'__tostring'   => 'language.oop5.magic',
			'__set_state'  => 'language.oop5.magic',
			'__debuginfo'  => 'language.oop5.magic',
			'__clone'      => 'language.oop5.cloning',
			
			'throw'     => 'language.exceptions',
			'try'       => 'language.exceptions',
			'catch'     => 'language.exceptions',
			'lsb'       => 'language.oop5.late-static-bindings',
			'namespace' => 'language.namespaces',
			'use'       => 'language.namespaces.using',
			'iterator'  => 'language.oop5.iterations',
			
			'factory'   => 'language.oop5.patterns',
			'singleton' => 'language.oop5.patterns',
			
			'trait'  => 'language.oop5.traits',
			'traits' => 'language.oop5.traits',
			
			'news.php'      => 'archive/index', // BC
			'readme.mirror' => 'mirroring', // BC
			
			'php5'                         => 'language.oop5',
			'zend_changes.txt'             => 'language.oop5', // BC
			'zend2_example.phps'           => 'language.oop5', // BC
			'zend_changes_php_5_0_0b2.txt' => 'language.oop5', // BC
			'zend-engine-2'                => 'language.oop5', // BC
			'zend-engine-2.php'            => 'language.oop5', // BC
			
			'news_php_5_0_0b2.txt' => 'ChangeLog-5', // BC
			'news_php_5_0_0b3.txt' => 'ChangeLog-5', // BC
			
			'manual/about-notes.php' => 'manual/add-note',   // BC
			'software/index.php'     => 'software',          // BC
			'releases.php'           => 'releases/index',    // BC
			
			'migration7'                      => 'migration70',      // Consistent with migration5
			'update_5_2.txt'                  => 'migration52',      // BC
			'readme_upgrade_51.php'           => 'migration51',      // BC
			'internals'                       => 'internals2',       // BC
			'configuration.directives'        => 'ini.core',       // BC
			
			# regexp. BC
			'regexp.reference.backslash'      => 'regexp.reference.escape',
			'regexp.reference.circudollar'    => 'regexp.reference.anchors',
			'regexp.reference.squarebrackets' => 'regexp.reference.character-classes',
			'regexp.reference.verticalbar'    => 'regexp.reference.alternation',
			
			# external shortcut aliases ;)
			'dochowto'                        => 'phpdochowto',
			
			# CVS -> SVN
			'anoncvs.php'                     => 'git',
			'cvs-php.php'                     => 'git-php',
			
			# SVN -> Git
			'svn'                             => 'git',
			'svn.php'                         => 'git',
			'svn-php'                         => 'git-php',
			'svn-php.php'                     => 'git-php',
			
			# CVSUp -> Nada
			'cvsup'                           => 'mirroring',
			
			# Other items
			'security/crypt'                  => 'security/crypt_blowfish',
			
			# Bugfixes
			'array_sort'                      => 'sort', // #64743
			'array-sort'                      => 'sort', // #64743
			
			# Removed pages
			'tips.php'                        => 'urlhowto',
			'tips'                            => 'urlhowto',
		];
		
		public const external_redirects = [
			'php4news'          => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-4.4',
			'php5news'          => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-5.6',
			'php53news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-5.3',
			'php54news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-5.4',
			'php55news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-5.5',
			'php56news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-5.6',
			'php70news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-7.0',
			'php71news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-7.1',
			'php72news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-7.2',
			'php73news'         => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/PHP-7.3',
			'phptrunknews'      => 'https://git.php.net/?p=php-src.git;a=blob_plain;f=NEWS;hb=refs/heads/master',
			'pear'              => 'http://pear.php.net/',
			'bugs'              => 'https://bugs.php.net/',
			'bugstats'          => 'https://bugs.php.net/stats.php',
			'phpdochowto'       => 'http://doc.php.net/tutorial/',
			'release/5_3_0.php' => '/releases/5_3_0.php', // PHP 5.3.0 release announcement had a typo
			'ideas.php'         => 'http://wiki.php.net/ideas', // BC
			'releases.atom'     => '/releases/feed.php', // BC, No need to pre-generate it
			'spec'              => 'https://github.com/php/php-langspec',
			'sunglasses'        => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Temporary easter egg for bug#66144
		];

		// Temporary hack to fix bug #49956 for mysqli -- Please don't hate me for this. Data taken from mysqli/summary.xml
		public const mysqli_redirects = [
			'mysqli_affected_rows'            => 'mysqli.affected-rows',
			'mysqli_get_client_info'          => 'mysqli.client-info',
			'mysqli_get_client_version'       => 'mysqli.client-version',
			'mysqli_connect_errno'            => 'mysqli.connect-errno',
			'mysqli_connect_error'            => 'mysqli.connect-error',
			'mysqli_errno'                    => 'mysqli.errno',
			'mysqli_error'                    => 'mysqli.error',
			'mysqli_field_count'              => 'mysqli.field-count',
			'mysqli_get_host_info'            => 'mysqli.host-info',
			'mysqli_get_proto_info'           => 'mysqli.protocol-version',
			'mysqli_get_server_info'          => 'mysqli.server-info',
			'mysqli_get_server_version'       => 'mysqli.server-version',
			'mysqli_info'                     => 'mysqli.info',
			'mysqli_insert_id'                => 'mysqli.insert-id',
			'mysqli_sqlstate'                 => 'mysqli.sqlstate',
			'mysqli_warning_count'            => 'mysqli.warning-count',
			'mysqli_autocommit'               => 'mysqli.autocommit',
			'mysqli_change_user'              => 'mysqli.change-user',
			'mysqli_character_set_name'       => 'mysqli.character-set-name',
			'mysqli_close'                    => 'mysqli.close',
			'mysqli_commit'                   => 'mysqli.commit',
			'mysqli_connect'                  => 'mysqli.construct',
			'mysqli_debug'                    => 'mysqli.debug',
			'mysqli_dump_debug_info'          => 'mysqli.dump-debug-info',
			'mysqli_get_charset'              => 'mysqli.get-charset',
			'mysqli_get_connection_stats'     => 'mysqli.get-connection-stats',
			'mysqli_get_client_info'          => 'mysqli.get-client-info',
			'mysqli_get_client_stats'         => 'mysqli.get-client-stats',
			'mysqli_get_cache_stats'          => 'mysqli.get-cache-stats',
			'mysqli_get_server_info'          => 'mysqli.get-server-info',
			'mysqli_get_warnings'             => 'mysqli.get-warnings',
			'mysqli_init'                     => 'mysqli.init',
			'mysqli_kill'                     => 'mysqli.kill',
			'mysqli_more_results'             => 'mysqli.more-results',
			'mysqli_multi_query'              => 'mysqli.multi-query',
			'mysqli_next_result'              => 'mysqli.next-result',
			'mysqli_options'                  => 'mysqli.options',
			'mysqli_ping'                     => 'mysqli.ping',
			'mysqli_prepare'                  => 'mysqli.prepare',
			'mysqli_query'                    => 'mysqli.query',
			'mysqli_real_connect'             => 'mysqli.real-connect',
			'mysqli_real_escape_string'       => 'mysqli.real-escape-string',
			'mysqli_real_query'               => 'mysqli.real-query',
			'mysqli_refresh'                  => 'mysqli.refresh',
			'mysqli_rollback'                 => 'mysqli.rollback',
			'mysqli_select_db'                => 'mysqli.select-db',
			'mysqli_set_charset'              => 'mysqli.set-charset',
			'mysqli_set_local_infile_default' => 'mysqli.set-local-infile-default',
			'mysqli_set_local_infile_handler' => 'mysqli.set-local-infile-handler',
			'mysqli_ssl_set'                  => 'mysqli.ssl-set',
			'mysqli_stat'                     => 'mysqli.stat',
			'mysqli_stmt_init'                => 'mysqli.stmt-init',
			'mysqli_store_result'             => 'mysqli.store-result',
			'mysqli_thread_id'                => 'mysqli.thread-id',
			'mysqli_thread_safe'              => 'mysqli.thread-safe',
			'mysqli_use_result'               => 'mysqli.use-result',
			'mysqli_stmt_affected_rows'       => 'mysqli-stmt.affected-rows',
			'mysqli_stmt_errno'               => 'mysqli-stmt.errno',
			'mysqli_stmt_error'               => 'mysqli-stmt.error',
			'mysqli_stmt_field_count'         => 'mysqli-stmt.field-count',
			'mysqli_stmt_insert_id'           => 'mysqli-stmt.insert-id',
			'mysqli_stmt_num_rows'            => 'mysqli-stmt.num-rows',
			'mysqli_stmt_param_count'         => 'mysqli-stmt.param-count',
			'mysqli_stmt_sqlstate'            => 'mysqli-stmt.sqlstate',
			'mysqli_stmt_attr_get'            => 'mysqli-stmt.attr-get',
			'mysqli_stmt_attr_set'            => 'mysqli-stmt.attr-set',
			'mysqli_stmt_bind_param'          => 'mysqli-stmt.bind-param',
			'mysqli_stmt_bind_result'         => 'mysqli-stmt.bind-result',
			'mysqli_stmt_close'               => 'mysqli-stmt.close',
			'mysqli_stmt_data_seek'           => 'mysqli-stmt.data-seek',
			'mysqli_stmt_execute'             => 'mysqli-stmt.execute',
			'mysqli_stmt_fetch'               => 'mysqli-stmt.fetch',
			'mysqli_stmt_free_result'         => 'mysqli-stmt.free-result',
			'mysqli_stmt_get_result'          => 'mysqli-stmt.get-result',
			'mysqli_stmt_get_warnings'        => 'mysqli-stmt.get-warnings',
			'mysqli_stmt_more_results'        => 'mysqli-stmt.more-results',
			'mysqli_stmt_next_result'         => 'mysqli-stmt.next-result',
			'mysqli_stmt_num_rows'            => 'mysqli-stmt.num-rows',
			'mysqli_stmt_prepare'             => 'mysqli-stmt.prepare',
			'mysqli_stmt_reset'               => 'mysqli-stmt.reset',
			'mysqli_stmt_result_metadata'     => 'mysqli-stmt.result-metadata',
			'mysqli_stmt_send_long_data'      => 'mysqli-stmt.send-long-data',
			'mysqli_stmt_store_result'        => 'mysqli-stmt.store-result',
			'mysqli_field_tell'               => 'mysqli-result.current-field',
			'mysqli_num_fields'               => 'mysqli-result.field-count',
			'mysqli_fetch_lengths'            => 'mysqli-result.lengths',
			'mysqli_num_rows'                 => 'mysqli-result.num-rows',
			'mysqli_data_seek'                => 'mysqli-result.data-seek',
			'mysqli_fetch_all'                => 'mysqli-result.fetch-all',
			'mysqli_fetch_array'              => 'mysqli-result.fetch-array',
			'mysqli_fetch_assoc'              => 'mysqli-result.fetch-assoc',
			'mysqli_fetch_field_direct'       => 'mysqli-result.fetch-field-direct',
			'mysqli_fetch_field'              => 'mysqli-result.fetch-field',
			'mysqli_fetch_fields'             => 'mysqli-result.fetch-fields',
			'mysqli_fetch_object'             => 'mysqli-result.fetch-object',
			'mysqli_fetch_row'                => 'mysqli-result.fetch-row',
			'mysqli_field_seek'               => 'mysqli-result.field-seek',
			'mysqli_free_result'              => 'mysqli-result.free',
			'mysqli_embedded_server_end'      => 'mysqli-driver.embedded-server-end',
			'mysqli_embedded_server_start'    => 'mysqli-driver.embedded-server-start',
		];
		
		public const KNOWN_INIS = array(
			'engine'						=> 'apache.configuration.php#ini.engine',
			'short-open-tag'				=> 'ini.core.php#ini.short-open-tag',
			'asp-tags'						=> 'ini.core.php#ini.asp-tags',
			'precision'						=> 'ini.core.php#ini.precision',
			'y2k-compliance'				=> 'ini.core.php#ini.y2k-compliance',
			'output-buffering'				=> 'outcontrol.configuration.php#ini.output-buffering',
			'output-handler'				=> 'outcontrol.configuration.php#ini.output-handler',
			'zlib.output-compression'		=> 'zlib.configuration.php#ini.zlib.output-compression',
			'zlib.output-compression-level'	=> 'zlib.configuration.php#ini.zlib.output-compression-level',
			'zlib.output-handler'			=> 'zlib.configuration.php#ini.zlib.output-handler',
			'implicit-flush'				=> 'outcontrol.configuration.php#ini.implicit-flush',
			'allow-call-time-pass-reference'=> 'ini.core.php#ini.allow-call-time-pass-reference',
			'safe-mode'						=> 'ini.sect.safe-mode.php#ini.safe-mode',
			'safe-mode-gid'					=> 'ini.sect.safe-mode.php#ini.safe-mode-gid',
			'safe-mode-include-dir'			=> 'ini.sect.safe-mode.php#ini.safe-mode-include-dir',
			'safe-mode-exec-dir'			=> 'ini.sect.safe-mode.php#ini.safe-mode-exec-dir',
			'safe-mode-allowed-env-vars'	=> 'ini.sect.safe-mode.php#ini.safe-mode-allowed-env-vars',
			'safe-mode-protected-env-vars'	=> 'ini.sect.safe-mode.php#ini.safe-mode-protected-env-vars',
			'open-basedir'					=> 'ini.core.php#ini.open-basedir',
			'disable-functions'				=> 'ini.core.php#ini.disable-functions',
			'disable-classes'				=> 'ini.core.php#ini.disable-classes',
			'syntax-highlighting'			=> 'misc.configuration.php#ini.syntax-highlighting',
			'ignore-user-abort'				=> 'misc.configuration.php#ini.ignore-user-abort',
			'realpath-cache-size'			=> 'ini.core.php#ini.realpath-cache-size',
			'realpath-cache-ttl'			=> 'ini.core.php#ini.realpath-cache-ttl',
			'expose-php'					=> 'ini.core.php#ini.expose-php',
			'max-execution-time'			=> 'info.configuration.php#ini.max-execution-time',
			'max-input-time'				=> 'info.configuration.php#ini.max-input-time',
			'max-input-nesting-level'		=> 'info.configuration.php#ini.max-input-nesting-level',
			'memory-limit'					=> 'ini.core.php#ini.memory-limit',
			'error-reporting'				=> 'errorfunc.configuration.php#ini.error-reporting',
			'display-errors'				=> 'errorfunc.configuration.php#ini.display-errors',
			'display-startup-errors'		=> 'errorfunc.configuration.php#ini.display-startup-errors',
			'log-errors'					=> 'errorfunc.configuration.php#ini.log-errors',
			'log-errors-max-len'			=> 'errorfunc.configuration.php#ini.log-errors-max-len',
			'ignore-repeated-errors'		=> 'errorfunc.configuration.php#ini.ignore-repeated-errors',
			'ignore-repeated-source'		=> 'errorfunc.configuration.php#ini.ignore-repeated-source',
			'report-memleaks'				=> 'errorfunc.configuration.php#ini.report-memleaks',
			'track-errors'					=> 'errorfunc.configuration.php#ini.track-errors',
			'xmlrpc-errors'					=> 'errorfunc.configuration.php#ini.xmlrpc-errors',
			'html-errors'					=> 'errorfunc.configuration.php#ini.html-errors',
			'docref-root'					=> 'errorfunc.configuration.php#ini.docref-root',
			'docref-ext'					=> 'errorfunc.configuration.php#ini.docref-ext',
			'error-prepend-string'			=> 'errorfunc.configuration.php#ini.error-prepend-string',
			'error-append-string'			=> 'errorfunc.configuration.php#ini.error-append-string',
			'error-log'						=> 'errorfunc.configuration.php#ini.error-log',
			'syslog.facility'				=> 'errorfunc.configuration.php#ini.syslog.facility',
			'syslog.filter'					=> 'errorfunc.configuration.php#ini.syslog.filter',
			'syslog.ident'					=> 'errorfunc.configuration.php#ini.syslog.ident',
			'arg-separator.output'			=> 'ini.core.php#ini.arg-separator.output',
			'arg-separator.input'			=> 'ini.core.php#ini.arg-separator.input',
			'variables-order'				=> 'ini.core.php#ini.variables-order',
			'request-order'					=> 'ini.core.php#ini.request-order',
			'register-globals'				=> 'ini.core.php#ini.register-globals',
			'register-long-arrays'			=> 'ini.core.php#ini.register-long-arrays',
			'register-argc-argv'			=> 'ini.core.php#ini.register-argc-argv',
			'auto-globals-jit'				=> 'ini.core.php#ini.auto-globals-jit',
			'post-max-size'					=> 'ini.core.php#ini.post-max-size',
			'magic-quotes-gpc'				=> 'info.configuration.php#ini.magic-quotes-gpc',
			'magic-quotes-runtime'			=> 'info.configuration.php#ini.magic-quotes-runtime',
			'magic-quotes-sybase'			=> 'sybase.configuration.php#ini.magic-quotes-sybase',
			'auto-prepend-file'				=> 'ini.core.php#ini.auto-prepend-file',
			'auto-append-file'				=> 'ini.core.php#ini.auto-append-file',
			'default-mimetype'				=> 'ini.core.php#ini.default-mimetype',
			'default-charset'				=> 'ini.core.php#ini.default-charset',
			'always-populate-raw-post-data'	=> 'ini.core.php#ini.always-populate-raw-post-data',
			'include-path'					=> 'ini.core.php#ini.include-path',
			'doc-root'						=> 'ini.core.php#ini.doc-root',
			'user-dir'						=> 'ini.core.php#ini.user-dir',
			'extension-dir'					=> 'ini.core.php#ini.extension-dir',
			'enable-dl'						=> 'info.configuration.php#ini.enable-dl',
			'cgi.force-redirect'			=> 'ini.core.php#ini.cgi.force-redirect',
			'cgi.redirect-status-env'		=> 'ini.core.php#ini.cgi.redirect-status-env',
			'cgi.fix-pathinfo'				=> 'ini.core.php#ini.cgi.fix-pathinfo',
			'fastcgi.impersonate'			=> 'ini.core.php#ini.fastcgi.impersonate',
			'cgi.rfc2616-headers'			=> 'ini.core.php#ini.cgi.rfc2616-headers',
			'file-uploads'					=> 'ini.core.php#ini.file-uploads',
			'upload-tmp-dir'				=> 'ini.core.php#ini.upload-tmp-dir',
			'upload-max-filesize'			=> 'ini.core.php#ini.upload-max-filesize',
			'allow-url-fopen'				=> 'filesystem.configuration.php#ini.allow-url-fopen',
			'allow-url-include'				=> 'filesystem.configuration.php#ini.allow-url-include',
			'from'							=> 'filesystem.configuration.php#ini.from',
			'user-agent'					=> 'filesystem.configuration.php#ini.user-agent',
			'default-socket-timeout'		=> 'filesystem.configuration.php#ini.default-socket-timeout',
			'auto-detect-line-endings'		=> 'filesystem.configuration.php#ini.auto-detect-line-endings',
			'date.timezone'					=> 'datetime.configuration.php#ini.date.timezone',
			'date.default-latitude'			=> 'datetime.configuration.php#ini.date.default-latitude',
			'date.default-longitude'		=> 'datetime.configuration.php#ini.date.default-longitude',
			'date.sunrise-zenith'			=> 'datetime.configuration.php#ini.date.sunrise-zenith',
			'date.sunset-zenith'			=> 'datetime.configuration.php#ini.date.sunset-zenith',
			'filter.default'				=> 'filter.configuration.php#ini.filter.default',
			'filter.default-flags'			=> 'filter.configuration.php#ini.filter.default-flags',
			'sqlite.assoc-case'				=> 'sqlite.configuration.php#ini.sqlite.assoc-case',
			'pcre.backtrack-limit'			=> 'pcre.configuration.php#ini.pcre.backtrack-limit',
			'pcre.recursion-limit'			=> 'pcre.configuration.php#ini.pcre.recursion-limit',
			'pdo-odbc.connection-pooling'	=> 'ref.pdo-odbc.php#ini.pdo-odbc.connection-pooling',
			'phar.readonly'					=> 'phar.configuration.php#ini.phar.readonly',
			'phar.require-hash'				=> 'phar.configuration.php#ini.phar.require-hash',
			'define-syslog-variables'		=> 'network.configuration.php#ini.define-syslog-variables',
			'smtp'							=> 'mail.configuration.php#ini.smtp',
			'smtp-port'						=> 'mail.configuration.php#ini.smtp-port',
			'sendmail-from'					=> 'mail.configuration.php#ini.sendmail-from',
			'sendmail-path'					=> 'mail.configuration.php#ini.sendmail-path',
			'sql.safe-mode'					=> 'ini.core.php#ini.sql.safe-mode',
			'odbc.default-db'				=> 'odbc.configuration.php#ini.uodbc.default-db',
			'odbc.default-user'				=> 'odbc.configuration.php#ini.uodbc.default-user',
			'odbc.default-pw'				=> 'odbc.configuration.php#ini.uodbc.default-pw',
			'odbc.allow-persistent'			=> 'odbc.configuration.php#ini.uodbc.allow-persistent',
			'odbc.check-persistent'			=> 'odbc.configuration.php#ini.uodbc.check-persistent',
			'odbc.max-persistent'			=> 'odbc.configuration.php#ini.uodbc.max-persistent',
			'odbc.max-links'				=> 'odbc.configuration.php#ini.uodbc.max-links',
			'odbc.defaultlrl'				=> 'odbc.configuration.php#ini.uodbc.defaultlrl',
			'odbc.defaultbinmode'			=> 'odbc.configuration.php#ini.uodbc.defaultbinmode',
			'mysql.allow-local-infile'              => 'mysql.configuration.php#ini.mysql.allow-local-infile',
			'mysql.allow-persistent'		=> 'mysql.configuration.php#ini.mysql.allow-persistent',
			'mysql.max-persistent'			=> 'mysql.configuration.php#ini.mysql.max-persistent',
			'mysql.max-links'				=> 'mysql.configuration.php#ini.mysql.max-links',
			'mysql.default-port'			=> 'mysql.configuration.php#ini.mysql.default-port',
			'mysql.default-socket'			=> 'mysql.configuration.php#ini.mysql.default-socket',
			'mysql.default-host'			=> 'mysql.configuration.php#ini.mysql.default-host',
			'mysql.default-user'			=> 'mysql.configuration.php#ini.mysql.default-user',
			'mysql.default-password'		=> 'mysql.configuration.php#ini.mysql.default-password',
			'mysql.connect-timeout'			=> 'mysql.configuration.php#ini.mysql.connect-timeout',
			'mysql.trace-mode'				=> 'mysql.configuration.php#ini.mysql.trace-mode',
			'mysqli.allow-local-infile'              => 'mysqli.configuration.php#ini.mysqli.allow-local-infile',
			'mysqli.max-links'				=> 'mysqli.configuration.php#ini.mysqli.max-links',
			'mysqli.allow-persistent'		=> 'mysqli.configuration.php#ini.mysqli.allow-persistent',
			'mysqli.default-port'			=> 'mysqli.configuration.php#ini.mysqli.default-port',
			'mysqli.default-socket'			=> 'mysqli.configuration.php#ini.mysqli.default-socket',
			'mysqli.default-host'			=> 'mysqli.configuration.php#ini.mysqli.default-host',
			'mysqli.default-user'			=> 'mysqli.configuration.php#ini.mysqli.default-user',
			'mysqli.default-pw'				=> 'mysqli.configuration.php#ini.mysqli.default-pw',
			'oci8.privileged-connect'		=> 'oci8.configuration.php#ini.oci8.privileged-connect',
			'oci8.max-persistent'			=> 'oci8.configuration.php#ini.oci8.max-persistent',
			'oci8.persistent-timeout'		=> 'oci8.configuration.php#ini.oci8.persistent-timeout',
			'oci8.ping-interval'			=> 'oci8.configuration.php#ini.oci8.ping-interval',
			'oci8.statement-cache-size'		=> 'oci8.configuration.php#ini.oci8.statement-cache-size',
			'oci8.default-prefetch'			=> 'oci8.configuration.php#ini.oci8.default-prefetch',
			'oci8.old-oci-close-semantics'	=> 'oci8.configuration.php#ini.oci8.old-oci-close-semantics',
			'opcache.preload'				=> 'opcache.configuration.php#ini.opcache.preload',
			'pgsql.allow-persistent'		=> 'pgsql.configuration.php#ini.pgsql.allow-persistent',
			'pgsql.auto-reset-persistent'	=> 'pgsql.configuration.php#ini.pgsql.auto-reset-persistent',
			'pgsql.max-persistent'			=> 'pgsql.configuration.php#ini.pgsql.max-persistent',
			'pgsql.max-links'				=> 'pgsql.configuration.php#ini.pgsql.max-links',
			'pgsql.ignore-notice'			=> 'pgsql.configuration.php#ini.pgsql.ignore-notice',
			'pgsql.log-notice'				=> 'pgsql.configuration.php#ini.pgsql.log-notice',
			'sqlite3.extension-dir'			=> 'sqlite3.configuration.php#ini.sqlite3.extension-dir',
			'sybct.allow-persistent'		=> 'sybase.configuration.php#ini.sybct.allow-persistent',
			'sybct.max-persistent'			=> 'sybase.configuration.php#ini.sybct.max-persistent',
			'sybct.max-links'				=> 'sybase.configuration.php#ini.sybct.max-links',
			'sybct.min-server-severity'		=> 'sybase.configuration.php#ini.sybct.min-server-severity',
			'sybct.min-client-severity'		=> 'sybase.configuration.php#ini.sybct.min-client-severity',
			'sybct.timeout'					=> 'sybase.configuration.php#ini.sybct.timeout',
			'bcmath.scale'					=> 'bc.configuration.php#ini.bcmath.scale',
			'browscap'						=> 'misc.configuration.php#ini.browscap',
			'session.save-handler'			=> 'session.configuration.php#ini.session.save-handler',
			'session.save-path'				=> 'session.configuration.php#ini.session.save-path',
			'session.use-cookies'			=> 'session.configuration.php#ini.session.use-cookies',
			'session.cookie-secure'			=> 'session.configuration.php#ini.session.cookie-secure',
			'session.use-only-cookies'		=> 'session.configuration.php#ini.session.use-only-cookies',
			'session.name'					=> 'session.configuration.php#ini.session.name',
			'session.auto-start'			=> 'session.configuration.php#ini.session.auto-start',
			'session.cookie-lifetime'		=> 'session.configuration.php#ini.session.cookie-lifetime',
			'session.cookie-path'			=> 'session.configuration.php#ini.session.cookie-path',
			'session.cookie-domain'			=> 'session.configuration.php#ini.session.cookie-domain',
			'session.cookie-httponly'		=> 'session.configuration.php#ini.session.cookie-httponly',
			'session.serialize-handler'		=> 'session.configuration.php#ini.session.serialize-handler',
			'session.gc-probability'		=> 'session.configuration.php#ini.session.gc-probability',
			'session.gc-divisor'			=> 'session.configuration.php#ini.session.gc-divisor',
			'session.gc-maxlifetime'		=> 'session.configuration.php#ini.session.gc-maxlifetime',
			'session.bug-compat-42'			=> 'session.configuration.php#ini.session.bug-compat-42',
			'session.bug-compat-warn'		=> 'session.configuration.php#ini.session.bug-compat-warn',
			'session.referer-check'			=> 'session.configuration.php#ini.session.referer-check',
			'session.entropy-length'		=> 'session.configuration.php#ini.session.entropy-length',
			'session.entropy-file'			=> 'session.configuration.php#ini.session.entropy-file',
			'session.cache-limiter'			=> 'session.configuration.php#ini.session.cache-limiter',
			'session.cache-expire'			=> 'session.configuration.php#ini.session.cache-expire',
			'session.use-trans-sid'			=> 'session.configuration.php#ini.session.use-trans-sid',
			'session.hash-function'			=> 'session.configuration.php#ini.session.hash-function',
			'session.hash-bits-per-character'       => 'session.configuration.php#ini.session.hash-bits-per-character',
			'session.upload-progress.enabled'       => 'session.configuration.php#ini.session.upload-progress.enabled',
			'session.upload-progress.cleanup'       => 'session.configuration.php#ini.session.upload-progress.cleanup',
			'session.upload-progress.prefix'        => 'session.configuration.php#ini.session.upload-progress.prefix',
			'session.upload-progress.name'          => 'session.configuration.php#ini.session.upload-progress.name',
			'session.upload-progress.freq'          => 'session.configuration.php#ini.session.upload-progress.freq',
			'session.upload-progress.min-freq'      => 'session.configuration.php#ini.session.upload-progress.min-freq',
			'url-rewriter.tags'				=> 'session.configuration.php#ini.url-rewriter.tags',
			'assert.active'					=> 'info.configuration.php#ini.assert.active',
			'assert.exception'				=> 'info.configuration.php#ini.assert.exception',
			'assert.warning'				=> 'info.configuration.php#ini.assert.warning',
			'assert.bail'					=> 'info.configuration.php#ini.assert.bail',
			'assert.callback'				=> 'info.configuration.php#ini.assert.callback',
			'assert.quiet-eval'				=> 'info.configuration.php#ini.assert.quiet-eval',
			'zend.enable-gc'				=> 'info.configuration.php#ini.zend.enable-gc',
			'com.typelib-file'				=> 'com.configuration.php#ini.com.typelib-file',
			'com.allow-dcom'				=> 'com.configuration.php#ini.com.allow-dcom',
			'com.autoregister-typelib'		=> 'com.configuration.php#ini.com.autoregister-typelib',
			'com.autoregister-casesensitive'=> 'com.configuration.php#ini.com.autoregister-casesensitive',
			'com.autoregister-verbose'		=> 'com.configuration.php#ini.com.autoregister-verbose',
			'mbstring.language'				=> 'mbstring.configuration.php#ini.mbstring.language',
			'mbstring.internal-encoding'	=> 'mbstring.configuration.php#ini.mbstring.internal-encoding',
			'mbstring.http-input'			=> 'mbstring.configuration.php#ini.mbstring.http-input',
			'mbstring.http-output'			=> 'mbstring.configuration.php#ini.mbstring.http-output',
			'mbstring.encoding-translation'	=> 'mbstring.configuration.php#ini.mbstring.encoding-translation',
			'mbstring.detect-order'			=> 'mbstring.configuration.php#ini.mbstring.detect-order',
			'mbstring.substitute-character'	=> 'mbstring.configuration.php#ini.mbstring.substitute-character',
			'mbstring.func-overload'		=> 'mbstring.configuration.php#ini.mbstring.func-overload',
			'gd.jpeg-ignore-warning'		=> 'image.configuration.php#ini.image.jpeg-ignore-warning',
			'exif.encode-unicode'			=> 'exif.configuration.php#ini.exif.encode-unicode',
			'exif.decode-unicode-motorola'	=> 'exif.configuration.php#ini.exif.decode-unicode-motorola',
			'exif.decode-unicode-intel'		=> 'exif.configuration.php#ini.exif.decode-unicode-intel',
			'exif.encode-jis'				=> 'exif.configuration.php#ini.exif.encode-jis',
			'exif.decode-jis-motorola'		=> 'exif.configuration.php#ini.exif.decode-jis-motorola',
			'exif.decode-jis-intel'			=> 'exif.configuration.php#ini.exif.decode-jis-intel',
			'tidy.default-config'			=> 'tidy.configuration.php#ini.tidy.default-config',
			'tidy.clean-output'				=> 'tidy.configuration.php#ini.tidy.clean-output',
			'soap.wsdl-cache-enabled'		=> 'soap.configuration.php#ini.soap.wsdl-cache-enabled',
			'soap.wsdl-cache-dir'			=> 'soap.configuration.php#ini.soap.wsdl-cache-dir',
			'soap.wsdl-cache-ttl'			=> 'soap.configuration.php#ini.soap.wsdl-cache-ttl',
		);
		
		public const KNOWN_VARIABLES = array(
			// Variables
			'globals'		=> 'reserved.variables.globals.php',
			'-server'		=> 'reserved.variables.server.php',
			'-get'			=> 'reserved.variables.get.php',
			'-post'			=> 'reserved.variables.post.php',
			'-files'		=> 'reserved.variables.files.php',
			'-request'		=> 'reserved.variables.request.php',
			'-session'		=> 'reserved.variables.session.php',
			'-cookie'		=> 'reserved.variables.cookies.php',
			'-env'			=> 'reserved.variables.environment.php',
			'this'			=> 'language.oop5.basic.php',
			'php-errormsg'	=> 'reserved.variables.phperrormsg.php',
			'argv'			=> 'reserved.variables.argv.php',
			'argc'			=> 'reserved.variables.argc.php',
			'http-raw-post-data'	=> 'reserved.variables.httprawpostdata.php',
			'http-response-header'	=> 'reserved.variables.httpresponseheader.php',
			'http-server-vars'		=> 'reserved.variables.server.php',
			'http-get-vars'			=> 'reserved.variables.get.php',
			'http-post-vars'		=> 'reserved.variables.post.php',
			'http-session-vars'		=> 'reserved.variables.session.php',
			'http-post-files'		=> 'reserved.variables.files.php',
			'http-cookie-vars'		=> 'reserved.variables.cookies.php',
			'http-env-vars'			=> 'reserved.variables.env.php',
		);
		
		public const KNOWN_TERMS = array(
			'<>'			=> 'language.operators.comparison.php',
			'=='			=> 'language.operators.comparison.php',
			'==='			=> 'language.operators.comparison.php',
			'@'				=> 'language.operators.errorcontrol.php',
			'apache'		=> 'install.php',
			'array'			=> 'language.types.array.php',
			'arrays'		=> 'language.types.array.php',
			'case'			=> 'control-structures.switch.php',
			'catch'			=> 'language.exceptions.php',
			'checkbox'		=> 'faq.html.php',
			'class'			=> 'language.oop5.basic.php',
			'classes'		=> 'language.oop5.basic.php',
			'closures'		=> 'functions.anonymous.php',
			'cookie'		=> 'features.cookies.php',
			'date'			=> 'function.date.php',
			'exception'		=> 'language.exceptions.php',
			'extends'		=> 'language.oop5.basic.php#language.oop5.basic.extends',
			'file'			=> 'function.file.php',
			'finally'		=> 'language.exceptions.php',
			'fopen'			=> 'function.fopen.php',
			'for'			=> 'control-structures.for.php',
			'foreach'		=> 'control-structures.foreach.php',
			'form'			=> 'language.variables.external.php',
			'forms'			=> 'language.variables.external.php',
			'function'		=> 'language.functions.php',
			'gd'			=> 'book.image.php',
			'get'			=> 'reserved.variables.get.php',
			'global'		=> 'language.variables.scope.php',
			'globals'		=> 'language.variables.scope.php',
			'header'		=> 'function.header.php',
			'heredoc'		=> 'language.types.string.php#language.types.string.syntax.heredoc',
			'nowdoc'		=> 'language.types.string.php#language.types.string.syntax.nowdoc',
			'htaccess'		=> 'configuration.file.php',
			'if'			=> 'control-structures.if.php',
			'include'		=> 'function.include.php',
			'int'			=> 'language.types.integer.php',
			'ip'			=> 'reserved.variables.server.php',
			'juggling'		=> 'language.types.type-juggling.php',
			'location'		=> 'function.header.php',
			'mail'			=> 'function.mail.php',
			'modulo'		=> 'language.operators.arithmetic.php',
			'mysql'			=> 'mysql.php',
			'new'			=> 'language.oop5.basic.php#language.oop5.basic.new',
			'null'			=> 'language.types.null.php',
			'object'		=> 'language.types.object.php',
			'operator'		=> 'language.operators.php',
			'operators'		=> 'language.operators.php',
			'or'			=> 'language.operators.logical.php',
			'php.ini'		=> 'configuration.file.php',
			'php-mysql.dll'	=> 'book.mysql.php',
			'php-self'		=> 'reserved.variables.server.php',
			'query-string'	=> 'reserved.variables.server.php',
			'redirect'		=> 'function.header.php',
			'reference'		=> 'index.php',
			'referer'		=> 'reserved.variables.server.php',
			'referrer'		=> 'reserved.variables.server.php',
			'remote-addr'	=> 'reserved.variables.server.php',
			'request'		=> 'reserved.variables.request.php',
			'session'		=> 'features.sessions.php',
			'smtp'			=> 'book.mail.php',
			'ssl'			=> 'book.openssl.php',
			'static'		=> 'language.oop5.static.php',
			'stdin'			=> 'wrappers.php.php',
			'string'		=> 'language.types.string.php',
			'superglobal'	=> 'language.variables.superglobals.php',
			'superglobals'	=> 'language.variables.superglobals.php',
			'switch'		=> 'control-structures.switch.php',
			'timestamp'		=> 'function.time.php',
			'try'			=> 'language.exceptions.php',
			'upload'		=> 'features.file-upload.php',
		);
	}